### Numpy基础

In [17]:
import numpy as np

In [3]:
array = [1,2,3,4,5]
array + =1

SyntaxError: invalid syntax (<ipython-input-3-8d66d45f806b>, line 2)

In [5]:
array = np.array([1,2,3,4,5])
print(type(array))


<class 'numpy.ndarray'>


In [6]:
array2 = array + 1
array2

array([2, 3, 4, 5, 6])

In [7]:
array2 + array

array([ 3,  5,  7,  9, 11])

In [8]:
array2 * array

array([ 2,  6, 12, 20, 30])

In [9]:
array.shape

(5,)

In [10]:
tang_list = [1,2,3,4,5]
tang_liat.shape

NameError: name 'tang_liat' is not defined

In [11]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)

In [24]:
tang_list = [1,2,3,4,'5']
tang_array = np.array(tang_list)

In [20]:
type(tang_array)

numpy.ndarray

In [21]:
tang_array.dtype

dtype('<U11')

In [25]:
tang_array.size

5

In [27]:
tang_array.ndim

1

In [28]:
tang_array[1:3]

array(['2', '3'], dtype='<U11')

In [29]:
tang_array[-2:]

array(['4', '5'], dtype='<U11')

### 创建数组

In [31]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [33]:
np.r_[0:5:1]

array([0, 1, 2, 3, 4])

In [34]:
np.c_[0:5:1]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### 生成任意数值的数组

In [39]:
#根据需求进行组合变化
np.ones((3,3))*8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [42]:
#也可以先创建一个空数组，制定好其大小 再往里面充值
a = np.empty(6)
#用数值1进行填充
a.fill(1)
a

array([1., 1., 1., 1., 1., 1.])

In [43]:
#先创建好一个数组 
tang_array = np.array([1,2,3,4])
#初始化一个零矩阵 让他和某个数组的维度一致
np.zeros_like(tang_array)

array([0, 0, 0, 0])

In [44]:
#只有对角线有数值 且为1
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
#其中（3,2）表示构建矩阵的大小
np.random.rand(3,2)

array([[0.28968766, 0.17026327],
       [0.57651334, 0.1443544 ],
       [0.22331911, 0.03376899]])

In [46]:
#返回区间（0,10）的随机整数
np.random.randint(10,size = (5,4))

array([[2, 5, 7, 6],
       [7, 0, 1, 0],
       [0, 9, 5, 0],
       [6, 5, 6, 7],
       [9, 1, 2, 8]])

In [48]:
#如果只想返回一个随机值
np.random.rand()

0.8921857668834438

In [49]:
#也可以自己指定区间 并选择随机的个数
np.random.randint(0,10,3)

array([5, 5, 8])

In [51]:
#符合均值为1 标准差为0.1的高斯分布的随机数
mu = 1
sigma = 0.1
np.random.normal(mu,sigma,10)

array([1.00530428, 1.04755274, 0.99652498, 1.06689638, 1.06174744,
       0.9705869 , 1.05091041, 0.89614922, 0.9620873 , 0.98122137])

In [52]:
#可以进行全局的设置 来控制结果的输出
np.set_printoptions(precision = 2)
np.random.normal(mu,sigma,10)

array([1.  , 1.15, 0.95, 0.96, 0.86, 0.83, 1.1 , 1.02, 1.05, 1.03])

In [58]:
tang_array = np.arange(10)
#每次执行的结果都是不一样的
np.random.shuffle(tang_array)
tang_array

array([3, 0, 8, 2, 7, 4, 6, 5, 9, 1])

In [63]:
np.random.seed(100)
np.random.normal(mu,sigma,10)

array([0.83, 1.03, 1.12, 0.97, 1.1 , 1.05, 1.02, 0.89, 0.98, 1.03])

### 文件读写

In [94]:
#Notebook的魔法指令 相当于写了一个文件
%%writefile tang.txt
123456
235879
#可以看本地是否创建了这个文件

UsageError: Line magic function `%%writefile` not found.


In [75]:
data = []
with open('tang.txt')as f:
    for line in f.readlines():
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 8., 7., 9.]])

In [76]:
data = np.loadtxt('tang.txt')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 8., 7., 9.]])

In [90]:
#如果数据中有分隔符
%%writefile tang3.txt
1,2,3,4,5,6
2,3,4,8,7,9

UsageError: Line magic function `%%writefile` not found.


In [ ]:
#读取的时候也需要制定好分隔符
data = np.loadtxt('tang2.txt,delimiter = ',',encoding='bytes')
data

In [92]:
%%writefile tang2.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,4,8,7,9

Overwriting tang2.txt


In [85]:
#可以指定去掉前几行
data = np.loadtxt('tang2.txt',delimiter = ',',skiprows = 1,encoding='bytes')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 8., 7., 9.]])

In [84]:
print(help(np.loadtxt))

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
  

In [97]:
np.savetxt('tang4.txt',tang_array,fmt='%d',delimiter=',')
#代码当前路径中多出一个文件 可以指定保存格式以及分隔符等

In [103]:
tang_array = np.array([[1,2,3],[4,5,6]])
#把结果保存成npy格式
np.save('tang_array.npy',tang_array)
#读取之前保存的结果 依旧是Numpy的数组格式
np.load('tang_array.npy',encoding='bytes')

array([[1, 2, 3],
       [4, 5, 6]])